services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_api
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      PRODUCTS_BASE_URL: ${PRODUCTS_BASE_URL}
      API_KEY: ${API_KEY}
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: