sonar.projectKey=TheAndrews_produtos-favoritos
sonar.organization=theandrews

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=\
    src/api/container/**,\
    src/api/docs/**,\
    src/api/forms/**,\
    src/api/middlewares/**,\
    src/api/router/**,\
    src/domain/interfaces/controllers/**,\
    src/domain/interfaces/repositories/**,\
    src/domain/interfaces/services/**,\
    src/domain/models/**,\
    src/infrastructure/config/**,\
    src/infrastructure/database/**,\
    src/internals/exceptions/**,\
    src/internals/mocks/**