// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "produtos-favoritos/src/domain/models"

	mock "github.com/stretchr/testify/mock"
)

// CustomerServicer is an autogenerated mock type for the CustomerServicer type
type CustomerServicer struct {
	mock.Mock
}

// CreateCustomer provides a mock function with given fields: customer
func (_m *CustomerServicer) CreateCustomer(customer *models.Customer) error {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCustomer provides a mock function with given fields: id
func (_m *CustomerServicer) DeleteCustomer(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCustomerByID provides a mock function with given fields: id
func (_m *CustomerServicer) GetCustomerByID(id string) (*models.Customer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerByID")
	}

	var r0 *models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Customer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Customer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCustomers provides a mock function with no fields
func (_m *CustomerServicer) ListCustomers() ([]models.Customer, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListCustomers")
	}

	var r0 []models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Customer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Customer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCustomer provides a mock function with given fields: id, customer
func (_m *CustomerServicer) UpdateCustomer(id string, customer *models.Customer) (*models.Customer, error) {
	ret := _m.Called(id, customer)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomer")
	}

	var r0 *models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *models.Customer) (*models.Customer, error)); ok {
		return rf(id, customer)
	}
	if rf, ok := ret.Get(0).(func(string, *models.Customer) *models.Customer); ok {
		r0 = rf(id, customer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *models.Customer) error); ok {
		r1 = rf(id, customer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerServicer creates a new instance of CustomerServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerServicer {
	mock := &CustomerServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
