// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// WishlistHandler is an autogenerated mock type for the WishlistHandler type
type WishlistHandler struct {
	mock.Mock
}

// RemoveFromWishlist provides a mock function with given fields: c
func (_m *WishlistHandler) RemoveFromWishlist(c *gin.Context) {
	_m.Called(c)
}

// WishlistProduct provides a mock function with given fields: c
func (_m *WishlistHandler) WishlistProduct(c *gin.Context) {
	_m.Called(c)
}

// NewWishlistHandler creates a new instance of WishlistHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWishlistHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *WishlistHandler {
	mock := &WishlistHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
