package router

import (
	_ "produtos-favoritos/src/api/docs" // docs is generated by Swag CLI, you must import it.
	"produtos-favoritos/src/api/middlewares"
	handlers "produtos-favoritos/src/domain/interfaces/controllers"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func SetupRouter(router *gin.Engine,
	customerController handlers.CustomerHandler,
	productController handlers.ProductHandler,
	wishlistContoller handlers.WishlistHandler) {
	// Define routes
	baseApiRoute := router.Group("api")
	{
		baseApiRoute.Use(middlewares.APIKeyMiddleware())
		v1Group := baseApiRoute.Group("v1")
		{
			customerGroup := v1Group.Group("/customers")
			{
				customerGroup.POST("/", customerController.Create)
				customerGroup.GET("/", customerController.List)
				customerGroup.GET("/:id", customerController.GetByID)
				customerGroup.PUT("/:id", customerController.Update)
				customerGroup.DELETE("/:id", customerController.Delete)

				customerGroup.POST("/:id/wishlist", wishlistContoller.WishlistProduct)
				customerGroup.DELETE("/:id/wishlist/:product_id", wishlistContoller.RemoveFromWishlist)
			}
			productGroup := v1Group.Group("/products")
			{
				productGroup.GET("/", productController.List)
			}
		}
	}

	// Swagger endpoint
	router.GET("/docs/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
}
